### ISSUE TITLE
ability to change a page's layout after creation

### ISSUE THREAD

**Issue by yoshokatana** [nymag/clay-kiln#318]
Is this something we want? Might be super useful, but might also be really difficult (and could potentially lose data if the layout people pick doesn't have things that the previous layout had). Might be better suited by #317

**Comment by TakenPilot** [comment]
I mentioned in a meeting with Kelly that it would in our interest to focus on copy and paste rather than this feature because of the "mapping" issue.  That is, how do we know how to map data between layouts, and what do we do with data that is "lost" when changing between a layout with three areas to a layout with two areas.

If we only have a finite amount of time for developers, I'd rather that time go toward copy and paste being ultra solid.

**Comment by yoshokatana** [comment]
Agreed, closing this.
