### ISSUE TITLE
save checkbox-group as an array

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#641]
e.g. PUT 
`['selected-val-1', 'selected-val-2']`
rather than 

```
{
  selected-val-1: true,
  selected-val-2: true,
  some-other-val: false
}
```

**Comment by nelsonpecora** [comment]
👎 I'm not super keen on this, for a few reasons:

* order doesn't matter in checkbox groups, which would be the main reason to switch to using arrays
* it's true that they're booleans (so an array could preserve the state just fine), but they're mostly accessed directly rather than looped over. putting them in an array wouldn't allow that

**Comment by cruzanmo** [comment]
The benefits of using arrays are easier indexing and reporting, and a smaller data-footprint. In the use-cases I have encountered, we do not care about the false state, so it is not useful data to store.

**Comment by nelsonpecora** [comment]
The data footprint is smaller, but it's a lot less clear. Plus, it seems we've started caring about false states in certain situations. I'm gonna close this for now, but we can revisit in the future?
