### ISSUE TITLE
Errors shown until publish pane until page is refreshed

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#786]
`paragraph>text` warning shows until page is refreshed.

Also, might be related, that there were errors for canonical url, meta description, and meta title in the publish pane and had to manually add the values.

**Comment by nelsonpecora** [comment]
Yup, the paragraph error was because of a thing we're doing when adding new components (the default data was being stored with the rest of the component data, rather than separately. This meant the validators were running on it). That's being fixed here https://github.com/nymag/clay-kiln/issues/778

As for the validation errors for head components, that's because multi-component updating isn't enabled for the article yet. We might have to re-add the old `component-ref` behavior if our components aren't updated before releasing kiln, but if so that'll work as before for legacy (non-pubsub) components
