### ISSUE TITLE
Editing Form Issue

### ISSUE THREAD

**Issue by jonwinton** [nymag/clay-kiln#807]
After editing any of the `Headlines and Teasers` in the article circulation area, you cannot immediately click into the `Article Metadata` section. 

Seems to only be breaking on new articles.

![screen shot 2017-04-13 at 1 19 23 pm](https://cloud.githubusercontent.com/assets/4906712/25015942/0737a4e0-204c-11e7-9644-5fd5140ab38a.png)

**Comment by nelsonpecora** [comment]
fixed in commit a269174

this occurred because the old way of preventing the global click handler from dispatching `unfocus` (when clicking out of things) didn't work correctly with the new event delegation. (Instead of setting `e.stopFocus` on a bubbling event, it was handling the click in the document, unfocusing, _then_ handling it again when clicking into the new form (this not seeing that there was a current form, and not waiting for the re-render loop to complete)

**Comment by jonwinton** [comment]
👍
